apiVersion: v1
kind: Service
metadata:
  labels:
    run: clinic
  name: clinic
spec:
  ports:
  - nodePort: 30773
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: clinic
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: clinic
  name: clinic
spec:
  replicas: 1
  selector:
    matchLabels:
      run: clinic
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: clinic
    spec:
      containers:
      - image: harbor.pgottam-demo.live/demobuild/spring-petclinic
        imagePullPolicy: Always
        name: clinic
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
